# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/workspace/workspace_zynq/zynq7020/PS_DEV/zynq_ps_code_gpio/gpio_mio/gpio_mio.srcs/sources_1/bd/zynq7/ip/zynq7_processing_system7_0_0/zynq7_processing_system7_0_0.xci
# IP: The module: 'zynq7_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/workspace/workspace_zynq/zynq7020/PS_DEV/zynq_ps_code_gpio/gpio_mio/gpio_mio.gen/sources_1/bd/zynq7/ip/zynq7_processing_system7_0_0/zynq7_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq7_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/workspace/workspace_zynq/zynq7020/PS_DEV/zynq_ps_code_gpio/gpio_mio/gpio_mio.srcs/sources_1/bd/zynq7/ip/zynq7_processing_system7_0_0/zynq7_processing_system7_0_0.xci
# IP: The module: 'zynq7_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/workspace/workspace_zynq/zynq7020/PS_DEV/zynq_ps_code_gpio/gpio_mio/gpio_mio.gen/sources_1/bd/zynq7/ip/zynq7_processing_system7_0_0/zynq7_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq7_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
