# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/workspace/workspace_zynq/zynq7020/PS_DEV/mio_intr/mio_intr.srcs/sources_1/bd/zynq7020/ip/zynq7020_processing_system7_0_0/zynq7020_processing_system7_0_0.xci
# IP: The module: 'zynq7020_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/workspace/workspace_zynq/zynq7020/PS_DEV/mio_intr/mio_intr.gen/sources_1/bd/zynq7020/ip/zynq7020_processing_system7_0_0/zynq7020_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq7020_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/workspace/workspace_zynq/zynq7020/PS_DEV/mio_intr/mio_intr.srcs/sources_1/bd/zynq7020/ip/zynq7020_processing_system7_0_0/zynq7020_processing_system7_0_0.xci
# IP: The module: 'zynq7020_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/workspace/workspace_zynq/zynq7020/PS_DEV/mio_intr/mio_intr.gen/sources_1/bd/zynq7020/ip/zynq7020_processing_system7_0_0/zynq7020_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq7020_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
